version: "3.9"

services:
  frontend:
    env_file: "./client/.env"

  mongo:
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: PassW0rd
      MONGO_INITDB_DATABASE: admin
    volumes:
      - mongo-data:/data/db

  backend:
    env_file: "./server/.env"
    depends_on:
      - mongo


volumes:
  app-data:
  mongo-data:
